<?xml version="1.0" encoding="utf-8"?><Database Name="SukobanGame" Class="QuanlyUserDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-F3VTH4B;Initial Catalog=SukobanGame;Integrated Security=True" SettingsObjectName="testProject.Properties.Settings" SettingsPropertyName="SukobanGameConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.dtbGame" Member="dtbGames">
    <Type Name="dtbGame">
      <Column Name="TaiKhoan" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="Point" Type="System.String" DbType="Char(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>